from django.urls import path
from  . import views
from rest_framework.urlpatterns import format_suffix_patterns
from .views import *


urlpatterns = [
    path ('',views.HomeView.as_view(), name='my_home_view'),
    path ('api_admin/',views.AdminView.as_view(),name="admin"),
    path ('distance/<int:pk>/<str:exclude_id>/<int:id_livraison>/', DistanceView.as_view(), name='my_distance_view'),
    path ('vider/',ViderListe.as_view(),name='vider'),
    path ('login/',views.UserLogin.as_view(), name='login'),
    path ('logout/',views.UserLogout.as_view(), name='logout'),
    path ('view/',views.UserView.as_view(), name='view'),
    path ('register/',views.UserRegister.as_view(), name='register'),
    path ('update/',views.UpdateUser.as_view(), name='update'),
    path ('update_password/',views.UpdatePassword.as_view(), name='update_password'),
    path ('articles/', ArticleListAPIView.as_view(), name='article_list'),
    path ('articles/<int:pk>/', ArticleDetailAPIView.as_view(), name='article_detail'),
    path ('address_livraison/',Adress_livraisonList.as_view(),name="addresse_livraison_View"),
    path ('address_livraison/<int:pk>/',Adress_livraisonById.as_view(),name='address_livraison_Byid_view'),
    path ('LigneLivraison/',LigneLivraisonList.as_view(),name="ligne_livraison_View"),
    path ('LigneLivraison/<int:pk>/',LigneLivraisonDetail.as_view(),name='ligne_livraison_Byid_view'),
    path ('Livraison/',LivraisonList.as_view(),name="livraison_View"),
    path ('Livraison/<int:pk>/',LivraisonDetail.as_view(),name='livraison_Byid_view'),
    path ('ListeProduits/',ListeProduitsAPI.as_view(),name="ListeProduits_View"),
    path ('ListeProduits/<int:pk>/',ListeProduitDetail.as_view(),name='ListeProduits_Byid_view'),
    path ('Produit-Article/<int:pk>/<int:quantite>/', ListeProduitArticle.as_view(), name='listProduits_byidArticle'),
    path ('distanceClientSupplier/<int:client_id>/<int:supplier_id>/', DistanceClientSupplier.as_view(), name='my_distance_view2'),
    path ('distanceClientFournisseur/<int:pk1>/<int:pk2>/', DistanceClientFournisseur.as_view(), name='my_distance_view2'),
    path ('distanceClientFournisseurMin/<str:fournisseurs_ids>/', DistanceMinFournisseurClient.as_view(), name='my_distance_view3'),
    path ('DistanceFournisseurFournisseur/<int:pk1>/<int:pk2>/', DistanceFournisseurFournisseur.as_view(), name='my_distance_view4'),
    path ('distanceClientLivreur/<int:pk1>/<int:pk2>/', DistanceLivreurClient.as_view(), name='my_distance_view4'),
    path ('distanceClientDelivrer/<int:supplier_id>/', DistanceSupplierDelivrer.as_view(), name='my_distance_view6'),
    path ('paniers/', PanierListCreateAPIView.as_view(), name='panier-list-create'),
    path ('paniers/<int:pk>/', PanierDetailAPIView.as_view(), name='panier-detail'),
    path ('lignes_panier/', LignePanierListCreateAPIView.as_view(), name='ligne-panier-list-create'),
    path ('lignes_panier/<int:pk>/', LignePanierDetailAPIView.as_view(), name='ligne-panier-detail'),
    path ('adresseLivraison/<int:client_id>/', Adresse_livraisonClient.as_view(), name='adrersseLivraisonClient'),
    path ('Fournisseur/<int:pk>/', FournisseurAPIViewID.as_view(), name='FournisseurbyId'),
    path ('Fournisseur/',FournisseurList.as_view(),name='fournisseurList'),
    path ('LivraisonBylivreur/',PanierListByLivreurAPIView.as_view(),name='livraison_By_livreurid_view'),
    path ('LivraisonByfournisseur/',FournisseurAPIView.as_view(),name='livraison_By_fournisseurid_view'),
    path ('client/<int:pk>/', ClientByid.as_view(), name='Client'),
    path ('client/',ClientList.as_view(),name='client'),
    path ('PrixLivraison/<int:pk>/',CalculerPrixLivraison.as_view(),name='prixLivraison'),
    path( "ligne/<int:panier_id>/",LignesPanierAPIView2.as_view(),name='ok'),
    path("livraisonvalide/",LivraisonValide.as_view(),name="valide"),
    path("LivreurAddress/<int:livreur_id>/",LivreurAddress.as_view(),name="valide"),
    path ('Livreur/',LivreurList.as_view(),name='livreur_list'),
    path ('Livreur/<int:pk>/',UpdateLivreurDetail.as_view(),name='livreur_update'),
    path ('Get_Road/<int:pk>/',GetLivreurRoad.as_view(),name='livreur_update'),
    path('listeProduit/',ListeProduitsByFournisseurAPIView.as_view(),name='liste_produit'),
    path('get_image/<int:image_id>/', get_image, name='get_image'),
    path('available-articles/', AvailableArticlesView.as_view(), name='available-articles'),
    path('not-shared-articles/<int:fournisseur_id>/', ArticlesNotSharedWithFournisseurView.as_view(), name='not-shared-articles'),
    path ('InitialAdresseLivraison/',InitialAdresseLivraisonClientDetail.as_view(),name='adresseclientinitiale'),
    path ('adressebyLivraison/<int:livraison_id>/',AdresseLivraisonbyLivraison.as_view(),name='adressebyLivraison'),
]
